# Generated by Django 3.1.14 on 2022-05-24 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_auto_20220524_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Pokemon',
            new_name='pokemon',
        ),
    ]
