# Generated by Django 3.1.14 on 2022-05-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_auto_20220525_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Ссылка на изображение'),
        ),
    ]
